# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  
  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - node.name=elasticsearch
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
   ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.9.2
   ports:
    - 5601:5601
   environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200

  logging:
    image: logging
    depends_on: [elasticsearch]
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:80

volumes:
  elasticsearch-data:
